services:
  phx:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    environment:
      - MIX_ENV=test
      - DATABASE_URL=ecto://pinchflat:pinchflat@pinchfork-db-ci/pinchflat
      - POOL_SIZE=5
    volumes:
      - '.:/app'
      # These lines ensure the deps can be saved as build artifacts for caching
      - '/app/deps'
      - '/app/_build'
    ports:
      - '4008:4008'
    command: tail -F /dev/null
    depends_on:
      pinchfork-db-ci:
        condition: service_healthy

  pinchfork-db-ci:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pinchflat
      POSTGRES_PASSWORD: pinchflat
      POSTGRES_DB: pinchflat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pinchflat"]
      interval: 5s
      timeout: 5s
      retries: 10
